name: Nginx Verify (Docker Nginx)
description: "Verify nginx config presence and container status/logs."

inputs:
  host: { required: true }
  user: { required: true }
  port: { required: false, default: "22" }

  nginx_container_name:
    required: false
    default: "nginx_proxy"

  service_name:
    required: true

  remove_service:
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Verify nginx service config
      uses: ./actions/ssh-run
      with:
        host: ${{ inputs.host }}
        user: ${{ inputs.user }}
        port: ${{ inputs.port }}
        script: |
          set -euo pipefail

          NGINX_CONTAINER="${{ inputs.nginx_container_name }}"
          SERVICE_NAME="${{ inputs.service_name }}"
          REMOVE_SERVICE="${{ inputs.remove_service }}"

          CONFIG_FILE="/opt/nginx/sites-enabled/service-$SERVICE_NAME.conf"

          echo "🔍 Verifying nginx config/service: $SERVICE_NAME"

          if [ "$REMOVE_SERVICE" = "true" ]; then
            if sudo test -f "$CONFIG_FILE"; then
              echo "❌ Config still exists (expected removed): $CONFIG_FILE"
              exit 1
            fi
            echo "✅ Config removed as expected."
          else
            if ! sudo test -f "$CONFIG_FILE"; then
              echo "❌ Config missing: $CONFIG_FILE"
              exit 1
            fi
            echo "✅ Config exists: $CONFIG_FILE"
            echo "   Lines: $(sudo wc -l < "$CONFIG_FILE")"
          fi

          echo ""
          echo "📦 Nginx container status:"
          sudo docker ps --filter "name=$NGINX_CONTAINER" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" || true

          echo ""
          echo "📝 Recent nginx logs:"
          sudo docker logs --tail=20 "$NGINX_CONTAINER" 2>/dev/null || true

          echo ""
          echo "📋 Active service configs:"
          ls -la /opt/nginx/sites-enabled/service-*.conf 2>/dev/null || echo "None"