name: Setup SSL Certificate (ACME-DNS)
description: "Provision and renew wildcard SSL certificates using acme-dns (DNS-01) and install a deploy hook to reload nginx container on renewals."

inputs:
  host: { required: true, description: "VPS hostname or IP" }
  user: { required: true, description: "SSH username" }
  port: { required: false, default: "22", description: "SSH port" }

  domain: { required: true, description: "Primary domain for the certificate (e.g., example.com)" }
  wildcard: { required: false, default: "true", description: "Include wildcard certificate (*.domain.com)" }

  acmedns_username: { required: true }
  acmedns_password: { required: true }
  acmedns_fulldomain: { required: true }
  acmedns_subdomain: { required: true }

  email: { required: true }
  certificates_dir: { required: false, default: "/etc/letsencrypt" }
  force_renewal: { required: false, default: "false" }

  nginx_container: { required: false, default: "" }

outputs:
  cert_path:
    value: "${{ steps.cert-paths.outputs.cert_path }}"
  key_path:
    value: "${{ steps.cert-paths.outputs.key_path }}"
  cert_dir:
    value: "${{ steps.cert-paths.outputs.cert_dir }}"

runs:
  using: "composite"
  steps:
    - name: Ensure action scripts exist
      shell: bash
      run: |
        set -euo pipefail
        test -f "${{ github.action_path }}/01-write-acmedns-creds.sh"
        test -f "${{ github.action_path }}/02-install-certbot.sh"
        test -f "${{ github.action_path }}/03-issue-cert.sh"

    - name: Setup ACME-DNS credentials on VPS
      shell: bash
      run: |
        set -euo pipefail
        cat "${{ github.action_path }}/01-write-acmedns-creds.sh" | \
        ssh -i ~/.ssh/id_rsa -p "${{ inputs.port }}" \
          -o StrictHostKeyChecking=yes \
          -o UserKnownHostsFile=~/.ssh/known_hosts \
          -o IdentitiesOnly=yes \
          -o LogLevel=ERROR \
          "${{ inputs.user }}@${{ inputs.host }}" \
          "DOMAIN='${{ inputs.domain }}' \
           ACMEDNS_USERNAME='${{ inputs.acmedns_username }}' \
           ACMEDNS_PASSWORD='${{ inputs.acmedns_password }}' \
           ACMEDNS_FULLDOMAIN='${{ inputs.acmedns_fulldomain }}' \
           ACMEDNS_SUBDOMAIN='${{ inputs.acmedns_subdomain }}' \
           CERT_DIR='${{ inputs.certificates_dir }}' \
           bash -se"

    - name: Install certbot + plugin on VPS
      shell: bash
      run: |
        set -euo pipefail
        cat "${{ github.action_path }}/02-install-certbot.sh" | \
        ssh -i ~/.ssh/id_rsa -p "${{ inputs.port }}" \
          -o StrictHostKeyChecking=yes \
          -o UserKnownHostsFile=~/.ssh/known_hosts \
          -o IdentitiesOnly=yes \
          -o LogLevel=ERROR \
          "${{ inputs.user }}@${{ inputs.host }}" \
          "bash -se"

    - name: Obtain / renew cert + deploy hook
      shell: bash
      run: |
        set -euo pipefail
        cat "${{ github.action_path }}/03-issue-cert.sh" | \
        ssh -i ~/.ssh/id_rsa -p "${{ inputs.port }}" \
          -o StrictHostKeyChecking=yes \
          -o UserKnownHostsFile=~/.ssh/known_hosts \
          -o IdentitiesOnly=yes \
          -o LogLevel=ERROR \
          "${{ inputs.user }}@${{ inputs.host }}" \
          "DOMAIN='${{ inputs.domain }}' \
           WILDCARD='${{ inputs.wildcard }}' \
           EMAIL='${{ inputs.email }}' \
           CERT_DIR='${{ inputs.certificates_dir }}' \
           FORCE_RENEWAL='${{ inputs.force_renewal }}' \
           NGINX_CONTAINER='${{ inputs.nginx_container }}' \
           bash -se"

    - name: Extract certificate paths
      id: cert-paths
      shell: bash
      run: |
        set -euo pipefail
        CERT_DIR="${{ inputs.certificates_dir }}"
        DOMAIN="${{ inputs.domain }}"
        echo "cert_path=$CERT_DIR/live/$DOMAIN/fullchain.pem" >> "$GITHUB_OUTPUT"
        echo "key_path=$CERT_DIR/live/$DOMAIN/privkey.pem" >> "$GITHUB_OUTPUT"
        echo "cert_dir=$CERT_DIR/live/$DOMAIN" >> "$GITHUB_OUTPUT"